<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_313586 results found in sneakers</name>
   <tag></tag>
   <elementGuidId>7baed1a0-875b-40a8-89f7-7fb4464f5db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.header__search-group-headline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-sx-search-results']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07c539ca-3f0a-4e97-9300-4c1b6bfae8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4d3502b6-16e0-4d29-8cdd-dcf0cd85509a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__search-group-headline</value>
      <webElementGuid>ca9df672-fa37-4f0b-be5f-74cb2592d830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vertical</name>
      <type>Main</type>
      <value>sneakers</value>
      <webElementGuid>3348ae98-9150-4df8-8bee-e643480d7853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>313586 results found in sneakers</value>
      <webElementGuid>89aa098b-1947-4003-bbe4-5afff2fc9b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-sx-search-results&quot;)/div[@class=&quot;header__search-group&quot;]/a[@class=&quot;header__search-group-headline&quot;]</value>
      <webElementGuid>b34ad785-b4bb-4483-8793-24d5b98177ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-sx-search-results']/div/a</value>
      <webElementGuid>8f32714d-b6fc-414e-9e29-d1c6090ebf6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop StockX'])[1]/following::a[1]</value>
      <webElementGuid>69a6b593-929b-4d90-85b9-15f9828dfca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[1]/following::a[2]</value>
      <webElementGuid>35493cec-57ab-4ea2-b91e-9730dc98b24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='apparel'])[1]/preceding::a[1]</value>
      <webElementGuid>81240f9b-db91-40c9-94dd-479c5f1158d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='results found in']/parent::*</value>
      <webElementGuid>e2629c80-ed3f-410e-8251-508e5a7a7077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>2256cc5d-3fd0-496e-b96a-aebbc3a1f984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>3228bea0-775a-48e2-8ecb-7ea7aadd017c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '313586 results found in sneakers' or . = '313586 results found in sneakers')]</value>
      <webElementGuid>b77a7ed6-473a-47a4-9864-4ea795a915c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
